In [1]:
import numpy as np
import pandas as pd
import calendar
data = pd.read_csv('D:\新零售\附件1.csv',encoding='gbk')
data["销量"] = '1'

data.loc[data['地点']=="A",'设备ID']="售货机A"
data.loc[data['地点']=="B",'设备ID']="售货机B"
data.loc[data['地点']=="C",'设备ID']="售货机C"
data.loc[data['地点']=="D",'设备ID']="售货机D"
data.loc[data['地点']=="E",'设备ID']="售货机E"  ##更改设备名称
data.to_csv('D:/新零售/附件0.csv',index=False)  ##index = False禁止生成文件时添加索引列“unnamed”

由于每台售货机与A,B,C,D,E五个地点是一一映射关系，所以通过“地点”修改设备名称，以便于查阅。

In [2]:
data0 = pd.read_csv('D:\新零售\附件0.csv')
test1 = data[data["地点"].str.contains('A')]  ##利用contains检查字符串并以此分类
test1.to_csv('D:/新零售/任务1A.csv',index=False,encoding='gbk')

test2 = data[data["地点"].str.contains('B')]
test2.to_csv('D:/新零售/任务1B.csv',index=False,encoding='gbk')

test3 = data[data["地点"].str.contains('C')]
test3.to_csv('D:/新零售/任务1C.csv',index=False,encoding='gbk')

test4 = data[data["地点"].str.contains('D')]
test4.to_csv('D:/新零售/任务1D.csv',index=False,encoding='gbk')

test5 = data[data["地点"].str.contains('E')]
test5.to_csv('D:/新零售/任务1E.csv',index=False,encoding='gbk')

data0["支付时间"]=pd.to_datetime(data0['支付时间'],format='%Y-%m-%d',errors='coerce')
data0 = data0.set_index('支付时间')  ##将“支付时间”设置为索引
data5 = data0['2017-05']
datagb = data5.groupby('设备ID')[['实际金额','销量']].sum()
datagb.loc['sum'] = datagb[['实际金额','销量']].agg(lambda x:x.sum(),axis=0)
datagb.to_csv('D:/新零售/销量金额.csv')
datagb

         实际金额      销量
设备ID
售货机A   3385.1   756.0
售货机B   3681.2   869.0
售货机C   3729.4   789.0
售货机D   2392.1   564.0
售货机E   5699.0  1292.0
sum   18886.8  4270.0

利用index=False阻止python生成文件时在首列添加索引列“unnamed 0”；通过set_index将“支付时间”设定为索引以至于可以直接抽取出2017年5月相关数据

In [3]:
data00 = data0.reset_index()  ##还原索引
data0ct = pd.crosstab(index=data00['设备ID'],columns=data00['支付时间'].apply(lambda m:m.month),values=data00['实际金额'],aggfunc=np.mean)
data0ct.to_csv('D:/新零售/每月每单均值.csv')
data0ct

支付时间,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0
设备ID,,,,,,,,,,,,
售货机A,4.506567,3.864035,3.585490,4.036913,4.477646,4.047394,4.097689,3.358709,4.307212,4.020703,4.471552,3.787868
售货机B,3.753005,3.255676,3.614717,4.075290,4.236133,4.068050,4.401739,3.584200,4.130258,4.112340,4.268784,3.667014
售货机C,4.328496,3.826087,3.769962,4.403678,4.726743,4.501700,3.988351,3.913582,4.427294,4.273330,4.352393,3.943043
售货机D,3.692664,3.088652,4.305729,3.790293,4.241312,4.025962,4.229653,3.316503,3.899390,3.884233,3.862314,3.572580
售货机E,4.680226,3.638372,4.305714,4.159888,4.410991,3.817856,3.919311,3.804471,4.125375,3.676125,4.283227,4.168973

前面我们用set_index将“支付时间”设置为索引，这里我们通过data00 = data0.reset_index()将其还原

In [4]:
datact = pd.crosstab(index=data00['设备ID'],columns=data00['支付时间'].apply(lambda m:m.month),values=data00['销量'],aggfunc=np.sum)
fenmu = calendar.mdays[1:]  ##生成一个包含每月天数的数组，数组第二个元素为1月的天数，所以用[1:]
daymean = datact.div(fenmu,axis=1)  ##series与dataframe相除
daymean.to_csv('D:/新零售/每月日均订单.csv')
daymean

支付时间,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0
设备ID,,,,,,,,,,,,
售货机A,10.806452,4.071429,8.225806,14.900000,24.387097,55.633333,15.354839,21.483871,34.666667,50.483871,38.666667,64.612903
售货机B,11.806452,6.607143,8.548387,20.100000,28.032258,61.866667,11.129032,31.645161,58.166667,65.354839,67.700000,71.290323
售货机C,12.225806,7.392857,8.483871,24.466667,25.451613,62.733333,24.645161,40.612903,55.933333,71.483871,64.766667,76.741935
售货机D,8.354839,5.035714,6.193548,14.766667,18.193548,34.666667,10.225806,23.064516,32.766667,38.258065,40.333333,53.645161
售货机E,11.419355,9.214286,11.290323,29.833333,41.677419,86.433333,26.225806,57.000000,137.800000,89.580645,167.333333,104.903226

datact是存有各个售货机每月销量之和的dataframe，我们导入calendar库，利用calendar.mdays[1:]得到每月天数的Series，在axis=1轴上相除既可。